### ISSUE TITLE
I ran into an error trying to install chiks

### ISSUE THREAD

**Issue by ajroberts0417** [SamuelRCrider/chiks#1]
When I ran `npm install -g chiks` i got this error:

npm ERR! code 1
npm ERR! path /Users/priyaghose/.nvm/versions/node/v21.6.1/lib/node_modules/chiks
npm ERR! command failed
npm ERR! command sh -c golang-npm install
npm ERR! Downloading from URL: https://github.com/SamuelRCrider/boilerplate-script/releases/download/v0.3.4/boilerplate-script_0.3.4_darwin_arm64.tar.gz
npm ERR! (node:91562) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! /Users/priyaghose/.nvm/versions/node/v21.6.1/lib/node_modules/chiks/node_modules/golang-npm/bin/index.js:161
npm ERR!       throw new Error("Error downloading binary. HTTP Status Code: " + res.status);
npm ERR!             ^
npm ERR!
npm ERR! Error: Error downloading binary. HTTP Status Code: 404
npm ERR!     at /Users/priyaghose/.nvm/versions/node/v21.6.1/lib/node_modules/chiks/node_modules/golang-npm/bin/index.js:161:13
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR!
npm ERR! Node.js v21.6.1

npm ERR! A complete log of this run can be found in: /Users/priyaghose/.npm/_logs/2024-07-10T17_58_03_625Z-debug-0.log

**Comment by SamuelRCrider** [comment]
This is so lit. I'll fix this now, it is because I just renamed the git repository.

**Comment by SamuelRCrider** [comment]
it's all fixed now.
