### ISSUE TITLE
Bug: Express server tries importing app routers from nonexistent directories

### ISSUE THREAD

**Issue by parth-agrawal** [SamuelRCrider/chiks#18]
I ran chiks and selected the following options:

1. Vite + Express
2. Clerk
3. React, Typescript
4. Yes Tailwind
5. Base Tailwind
6. (changed entry point to index.ts in backend package.json config)
7.  Yes Postgres Database

An additional note - I was unable to run the frontend until I installed `npm install --save-dev @vitejs/plugin-react-swc` .  

But when I opened up the backend, it attempted to import a userRouter from a controller library that doesn't exist. Here's the app.ts file that was generated:  
![Screenshot 2024-07-31 at 4 44 29 PM](https://github.com/user-attachments/assets/560cc9e9-f528-4cee-86a3-4b72568a5e4a)

And here's the generated folder structure (no `lib/controllers`): 
![Screenshot 2024-07-31 at 4 45 44 PM](https://github.com/user-attachments/assets/47226684-2978-4c46-9543-3a1c71202a05)

The error I would get if I tried running the server: 
![Screenshot 2024-07-31 at 4 47 51 PM](https://github.com/user-attachments/assets/6459ae91-66e6-4ecd-91cf-896fa9b9eb03)

**Comment by parth-agrawal** [comment]
oh, also, the app.ts doesn't have a `listen` command that would allow the express server to listen on e.g. Port 3000

**Comment by SamuelRCrider** [comment]
A fix is in the works for this.

**Comment by SamuelRCrider** [comment]
This is now fixed, will update npm soon.
