### ISSUE TITLE
At the end of boilerplate creation, migration fails

### ISSUE THREAD

**Issue by parth-agrawal** [SamuelRCrider/chiks#19]
I ran chiks and selected the following options:

1. Vite + Express
2. Clerk
3. React, Typescript
4. Yes Tailwind
5. Base Tailwind
6. (changed entry point to index.ts in backend package.json config)
7.  Yes Postgres Database

After this final step, it looks like it attempted to run an initial migration, but this failed. Here's the error I got:
![Screenshot 2024-07-31 at 4 48 09 PM](https://github.com/user-attachments/assets/e17f5fcd-b436-4cc5-9e5a-223cb4e199b5)

Once I ran `docker compose up` and `npx prisma migrate dev` myself, it largely worked (I needed to select an option to allow it to clear data first). So in this boilerplate sequence you probably need to add a `docker compose up` command.

**Comment by SamuelRCrider** [comment]
This issue is fixed. There was an underlying problem with the docker compose files I was generating for boilerplate.
