### ISSUE TITLE
I ran into an error where, when I was missing the `create-vite` command, the creating frontend section never completed (infinite hang).

### ISSUE THREAD

**Issue by ajroberts0417** [SamuelRCrider/chiks#2]
Need to install the following packages:
create-vite@5.3.0
| Creating frontend...npm ERR! canceled

npm ERR! A complete log of this run can be found in: /Users/priyaghose/.npm/_logs/2024-07-10T18_20_30_591Z-debug-0.log
exit status 1

<img width="860" alt="Screenshot 2024-07-10 at 2 27 24 PM" src="https://github.com/SamuelRCrider/chiks/assets/25114792/82f8ccb2-2ad8-41f3-b21c-fb50b13c787c">

otherwise this is great, nice work!

**Comment by SamuelRCrider** [comment]
a fix is on the way.

**Comment by SamuelRCrider** [comment]
This issue is resolved. However, it will not go live until this evening. Thanks for making issues! It is super nice to be getting feedback on my package.
